<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.10.12 on win32)" generated="20240411 09:31:42.627" rpa="false" schemaversion="4">
<suite id="s1" name="Datadriven" source="d:\Self\VScode\py\day9\datadriven.robot">
<kw name="Open my Browser" library="datadriven_keywords" type="SETUP">
<arg>${platform_url}</arg>
<arg>${platform_browser}</arg>
<kw name="Open Browser" library="SeleniumLibrary">
<arg>${url}</arg>
<arg>${browser}</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20240411 09:31:43.679" level="INFO">Opening browser 'chrome' to base url 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.</msg>
<status status="PASS" starttime="20240411 09:31:43.677" endtime="20240411 09:31:49.515"/>
</kw>
<kw name="Maximize Browser Window" library="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" starttime="20240411 09:31:49.516" endtime="20240411 09:31:49.626"/>
</kw>
<status status="PASS" starttime="20240411 09:31:43.676" endtime="20240411 09:31:49.627"/>
</kw>
<test id="s1-t1" name="LoginTestwithExcel using" line="18">
<kw name="Invalid login">
<arg>${username}</arg>
<arg>${password}</arg>
<msg timestamp="20240411 09:31:49.632" level="FAIL">Variable '${username}' not found.</msg>
<status status="FAIL" starttime="20240411 09:31:49.630" endtime="20240411 09:31:49.634"/>
</kw>
<status status="FAIL" starttime="20240411 09:31:49.627" endtime="20240411 09:31:49.635">Variable '${username}' not found.</status>
</test>
<kw name="Close my browser" library="datadriven_keywords" type="TEARDOWN">
<kw name="Close Browser" library="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="PASS" starttime="20240411 09:31:49.638" endtime="20240411 09:31:52.098"/>
</kw>
<status status="PASS" starttime="20240411 09:31:49.637" endtime="20240411 09:31:52.098"/>
</kw>
<status status="FAIL" starttime="20240411 09:31:42.639" endtime="20240411 09:31:52.099"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Datadriven">Datadriven</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20240411 09:31:43.671" level="ERROR">[ DataDriver ] Error in robot file:
  File "d:\Self\VScode\py\day9\datadriven.robot", line 0</msg>
<msg timestamp="20240411 09:31:43.672" level="ERROR">In source file:
  File "day9/Testdata.xlsx", line 0</msg>
<msg timestamp="20240411 09:31:43.675" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: ImportError: Requirements (pandas, openpyxl) for XLSX support are not installed.
    Use 'pip install -U robotframework-datadriver[XLS]' to install XLSX support.</msg>
</errors>
</robot>
